package entidades;
// Generated 10/06/2023 02:55:46 by Hibernate Tools 4.3.1



/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private Integer codAdministrador;
     private String nomeAdministrador;
     private String login;
     private String senha;

    public Administrador() {
    }

    public Administrador(String nomeAdministrador, String login, String senha) {
       this.nomeAdministrador = nomeAdministrador;
       this.login = login;
       this.senha = senha;
    }
   
    public Integer getCodAdministrador() {
        return this.codAdministrador;
    }
    
    public void setCodAdministrador(Integer codAdministrador) {
        this.codAdministrador = codAdministrador;
    }
    public String getNomeAdministrador() {
        return this.nomeAdministrador;
    }
    
    public void setNomeAdministrador(String nomeAdministrador) {
        this.nomeAdministrador = nomeAdministrador;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


