package entidades;
// Generated 04/05/2023 13:33:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private Endereco endereco;
     private Telefone telefone;
     private String nomeCliente;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Endereco endereco, Telefone telefone) {
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Cliente(Endereco endereco, Telefone telefone, String nomeCliente, Set vendas) {
       this.endereco = endereco;
       this.telefone = telefone;
       this.nomeCliente = nomeCliente;
       this.vendas = vendas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


