package entidades;
// Generated 07/06/2023 19:57:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private Conta conta;
     private Endereco endereco;
     private Telefone telefone;
     private String nomeCliente;
     private String cpf;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Conta conta, Endereco endereco, Telefone telefone) {
        this.conta = conta;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Cliente(Conta conta, Endereco endereco, Telefone telefone, String nomeCliente, String cpf, Set vendas) {
       this.conta = conta;
       this.endereco = endereco;
       this.telefone = telefone;
       this.nomeCliente = nomeCliente;
       this.cpf = cpf;
       this.vendas = vendas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


