package entidades;
// Generated 10/06/2023 02:55:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private String nomeCliente;
     private String cpf;
     private String bairro;
     private String logradouro;
     private String numero;
     private String cep;
     private String cidade;
     private String uf;
     private String numTelefone;
     private String login;
     private String senha;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String bairro, String logradouro) {
        this.bairro = bairro;
        this.logradouro = logradouro;
    }
    public Cliente(String nomeCliente, String cpf, String bairro, String logradouro, String numero, String cep, String cidade, String uf, String numTelefone, String login, String senha, Set vendas) {
       this.nomeCliente = nomeCliente;
       this.cpf = cpf;
       this.bairro = bairro;
       this.logradouro = logradouro;
       this.numero = numero;
       this.cep = cep;
       this.cidade = cidade;
       this.uf = uf;
       this.numTelefone = numTelefone;
       this.login = login;
       this.senha = senha;
       this.vendas = vendas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getNumTelefone() {
        return this.numTelefone;
    }
    
    public void setNumTelefone(String numTelefone) {
        this.numTelefone = numTelefone;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


