package entidades;
// Generated 06/06/2023 09:26:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Conta generated by hbm2java
 */
public class Conta  implements java.io.Serializable {


     private Integer codConta;
     private Acesso acesso;
     private String login;
     private String senha;
     private Set clientes = new HashSet(0);
     private Set fornecedors = new HashSet(0);

    public Conta() {
    }

	
    public Conta(Acesso acesso) {
        this.acesso = acesso;
    }
    public Conta(Acesso acesso, String login, String senha, Set clientes, Set fornecedors) {
       this.acesso = acesso;
       this.login = login;
       this.senha = senha;
       this.clientes = clientes;
       this.fornecedors = fornecedors;
    }
   
    public Integer getCodConta() {
        return this.codConta;
    }
    
    public void setCodConta(Integer codConta) {
        this.codConta = codConta;
    }
    public Acesso getAcesso() {
        return this.acesso;
    }
    
    public void setAcesso(Acesso acesso) {
        this.acesso = acesso;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }




}


