package entidades;
// Generated 10/06/2023 02:55:46 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer codFornecedor;
     private String nomeFornecedor;
     private String cnpj;
     private String bairro;
     private String logradouro;
     private String numero;
     private String cep;
     private String cidade;
     private String uf;
     private String numTelefone;
     private String login;
     private String senha;

    public Fornecedor() {
    }

	
    public Fornecedor(String bairro, String logradouro) {
        this.bairro = bairro;
        this.logradouro = logradouro;
    }
    public Fornecedor(String nomeFornecedor, String cnpj, String bairro, String logradouro, String numero, String cep, String cidade, String uf, String numTelefone, String login, String senha) {
       this.nomeFornecedor = nomeFornecedor;
       this.cnpj = cnpj;
       this.bairro = bairro;
       this.logradouro = logradouro;
       this.numero = numero;
       this.cep = cep;
       this.cidade = cidade;
       this.uf = uf;
       this.numTelefone = numTelefone;
       this.login = login;
       this.senha = senha;
    }
   
    public Integer getCodFornecedor() {
        return this.codFornecedor;
    }
    
    public void setCodFornecedor(Integer codFornecedor) {
        this.codFornecedor = codFornecedor;
    }
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getNumTelefone() {
        return this.numTelefone;
    }
    
    public void setNumTelefone(String numTelefone) {
        this.numTelefone = numTelefone;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


