package entidades;
// Generated 04/05/2023 13:33:19 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer codFornecedor;
     private Endereco endereco;
     private Telefone telefone;
     private String nomeFornecedor;
     private Integer cnpj;

    public Fornecedor() {
    }

	
    public Fornecedor(Endereco endereco, Telefone telefone) {
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Fornecedor(Endereco endereco, Telefone telefone, String nomeFornecedor, Integer cnpj) {
       this.endereco = endereco;
       this.telefone = telefone;
       this.nomeFornecedor = nomeFornecedor;
       this.cnpj = cnpj;
    }
   
    public Integer getCodFornecedor() {
        return this.codFornecedor;
    }
    
    public void setCodFornecedor(Integer codFornecedor) {
        this.codFornecedor = codFornecedor;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }
    public Integer getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(Integer cnpj) {
        this.cnpj = cnpj;
    }




}


