package entidades;
// Generated 06/06/2023 09:26:01 by Hibernate Tools 4.3.1



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer codFornecedor;
     private Conta conta;
     private Endereco endereco;
     private Telefone telefone;
     private String nomeFornecedor;
     private String cnpj;

    public Fornecedor() {
    }

	
    public Fornecedor(Conta conta, Endereco endereco, Telefone telefone) {
        this.conta = conta;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Fornecedor(Conta conta, Endereco endereco, Telefone telefone, String nomeFornecedor, String cnpj) {
       this.conta = conta;
       this.endereco = endereco;
       this.telefone = telefone;
       this.nomeFornecedor = nomeFornecedor;
       this.cnpj = cnpj;
    }
   
    public Integer getCodFornecedor() {
        return this.codFornecedor;
    }
    
    public void setCodFornecedor(Integer codFornecedor) {
        this.codFornecedor = codFornecedor;
    }
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Telefone getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Telefone telefone) {
        this.telefone = telefone;
    }
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }




}


